<?php
/** Public, two-step withdrawal declarations; no login or automatic refund. */
if ( ! defined( 'ABSPATH' ) ) { exit; }
add_action( 'init', function() {
 register_post_type( 'candy_withdrawal', array(
  'labels' => array( 'name' => 'Widerrufe', 'singular_name' => 'Widerruf' ), 'public' => false,
  'show_ui' => true, 'show_in_rest' => false, 'show_in_menu' => 'woocommerce', 'supports' => array( 'title', 'editor' ),
  'capabilities' => array( 'edit_post' => 'manage_woocommerce', 'read_post' => 'manage_woocommerce', 'delete_post' => 'manage_woocommerce', 'edit_posts' => 'manage_woocommerce', 'edit_others_posts' => 'manage_woocommerce', 'publish_posts' => 'manage_woocommerce', 'read_private_posts' => 'manage_woocommerce', 'delete_posts' => 'manage_woocommerce', 'create_posts' => 'do_not_allow' ), 'map_meta_cap' => false,
 ) );
} );
function candy_withdrawal_fields( $input ) {
 $values = array();
 foreach ( array( 'name' => 150, 'contract' => 2000, 'email' => 254 ) as $key => $max ) {
  $value = $input[$key] ?? '';
  if ( ! is_string( $value ) || strlen( $value ) > $max * 4 ) { throw new Exception( 'Bitte prüfe die Länge deiner Eingaben.' ); }
  $values[$key] = trim( 'contract' === $key ? sanitize_textarea_field( $value ) : sanitize_text_field( $value ) );
  if ( ! $values[$key] || mb_strlen( $values[$key] ) > $max ) { throw new Exception( 'Bitte fülle alle Felder innerhalb der angegebenen Länge aus.' ); }
 }
 if ( ! is_email( $values['email'] ) ) { throw new Exception( 'Bitte gib eine gültige E-Mail-Adresse für die Bestätigung ein.' ); }
 return $values;
}
function candy_record_withdrawal( $values, $token ) {
 // Token is generated by this form and signed with a server secret. A repeat
 // submission returns the same receipt instead of sending duplicate emails.
 if ( ! preg_match( '/^[a-f0-9-]{36}$/', $token ) ) { throw new Exception( 'Bitte öffne das Formular erneut.' ); }
 $existing = get_posts( array( 'post_type' => 'candy_withdrawal', 'post_status' => 'private', 'meta_key' => '_candy_token', 'meta_value' => $token, 'numberposts' => 1 ) );
 if ( $existing ) { return $existing[0]->ID; }
 $time = wp_date( 'd.m.Y H:i:s T' );
 $text = "Eingangsbestätigung Ihres Widerrufs\n\nHiermit widerrufe ich den folgenden Vertrag bzw. die angegebenen Artikel.\n\nName: " . $values['name'] . "\nVertrag / Artikel: " . $values['contract'] . "\nE-Mail für die Bestätigung: " . $values['email'] . "\nEingegangen: " . $time . "\n\nDiese Nachricht bestätigt den Eingang Ihrer Erklärung. Eine etwaige Rückzahlung wird gesondert bearbeitet.";
 $id = wp_insert_post( array( 'post_type' => 'candy_withdrawal', 'post_status' => 'private', 'post_title' => 'Widerruf vom ' . $time, 'post_content' => $text, 'meta_input' => array( '_candy_token' => $token, '_candy_receipt_email' => $values['email'], '_candy_receipt_time' => $time, '_candy_customer_sent' => 'no', '_candy_merchant_sent' => 'no' ) ), true );
 if ( is_wp_error( $id ) || ! $id ) { throw new Exception( 'Dein Widerruf konnte nicht gespeichert werden. Bitte versuche es erneut oder nutze die Kontaktadresse im Impressum.' ); }
 candy_deliver_withdrawal( $id );
 return $id;
}
function candy_deliver_withdrawal( $id ) {
 $post = get_post( $id ); if ( ! $post || 'candy_withdrawal' !== $post->post_type ) { return; }
 foreach ( array( 'customer' => get_post_meta( $id, '_candy_receipt_email', true ), 'merchant' => get_option( 'admin_email' ) ) as $role => $email ) {
  if ( 'yes' === get_post_meta( $id, '_candy_' . $role . '_sent', true ) ) { continue; }
  if ( wp_mail( $email, 'Candy Corner – Widerruf eingegangen #' . $id, $post->post_content, array( 'Content-Type: text/plain; charset=UTF-8' ) ) ) { update_post_meta( $id, '_candy_' . $role . '_sent', 'yes' ); }
 }
 if ( 'yes' !== get_post_meta( $id, '_candy_customer_sent', true ) || 'yes' !== get_post_meta( $id, '_candy_merchant_sent', true ) ) {
  if ( ! wp_next_scheduled( 'candy_retry_withdrawal', array( $id ) ) ) { wp_schedule_single_event( time() + 300, 'candy_retry_withdrawal', array( $id ) ); }
 }
}
add_action( 'candy_retry_withdrawal', 'candy_deliver_withdrawal' );
add_action( 'admin_notices', function() {
 if ( ! current_user_can( 'manage_woocommerce' ) ) { return; }
 $failed = get_posts( array( 'post_type' => 'candy_withdrawal', 'post_status' => 'private', 'numberposts' => 1, 'meta_query' => array( 'relation' => 'OR', array( 'key' => '_candy_customer_sent', 'value' => 'no' ), array( 'key' => '_candy_merchant_sent', 'value' => 'no' ) ) ) );
 if ( $failed ) { echo '<div class="notice notice-error"><p><strong>Widerruf gespeichert, E-Mail-Versand offen.</strong> Bitte unter WooCommerce → Widerrufe prüfen und die Eingangsbestätigung unverzüglich zustellen. SMTP und WP-Cron prüfen.</p></div>'; }
} );
add_action( 'template_redirect', function() {
 if ( is_page() && has_shortcode( get_post()->post_content, 'candy_withdrawal' ) ) {
  if ( ! defined( 'DONOTCACHEPAGE' ) ) { define( 'DONOTCACHEPAGE', true ); }
  nocache_headers();
 }
} );
add_shortcode( 'candy_withdrawal', function() {
 $stage = 'enter'; $error = ''; $values = array( 'name' => '', 'contract' => '', 'email' => '' );
 $token = wp_generate_uuid4(); $id = 0;
 if ( 'POST' === ( $_SERVER['REQUEST_METHOD'] ?? '' ) && isset( $_POST['candy_withdrawal_stage'] ) ) {
  try {
   $nonce = isset( $_POST['_wpnonce'] ) && is_string( $_POST['_wpnonce'] ) ? wp_unslash( $_POST['_wpnonce'] ) : '';
   if ( ! wp_verify_nonce( $nonce, 'candy_withdrawal' ) ) { throw new Exception( 'Das Formular ist abgelaufen. Bitte gib deine Daten erneut ein.' ); }
   $values = candy_withdrawal_fields( array( 'name' => wp_unslash( $_POST['withdrawal_name'] ?? '' ), 'contract' => wp_unslash( $_POST['withdrawal_contract'] ?? '' ), 'email' => wp_unslash( $_POST['withdrawal_email'] ?? '' ) ) );
   $token = isset( $_POST['token'] ) && is_string( $_POST['token'] ) ? sanitize_text_field( wp_unslash( $_POST['token'] ) ) : '';
   $signature = isset( $_POST['signature'] ) && is_string( $_POST['signature'] ) ? wp_unslash( $_POST['signature'] ) : '';
   if ( ! hash_equals( hash_hmac( 'sha256', $token, wp_salt() ), $signature ) ) { throw new Exception( 'Bitte öffne das Formular erneut.' ); }
   if ( 'confirm' === $_POST['candy_withdrawal_stage'] ) { $id = candy_record_withdrawal( $values, $token ); $stage = 'done'; } else { $stage = 'review'; }
  } catch ( Exception $e ) { $error = $e->getMessage(); $token = wp_generate_uuid4(); }
 }
 ob_start();
 echo '<div class="candy-withdrawal-form">';
 if ( $error ) { echo '<p role="alert">' . esc_html( $error ) . '</p>'; }
 if ( 'done' === $stage ) {
  echo '<h2>Dein Widerruf ist eingegangen.</h2><p>Referenz: ' . absint( $id ) . ' · ' . esc_html( get_post_meta( $id, '_candy_receipt_time', true ) ) . '</p>';
  echo '<p>' . ( 'yes' === get_post_meta( $id, '_candy_customer_sent', true ) ? 'Die Eingangsbestätigung wurde zum E-Mail-Versand übergeben. Bitte prüfe auch deinen Spam-Ordner.' : 'Deine Erklärung ist gespeichert. Der E-Mail-Versand konnte noch nicht abgeschlossen werden; wir versuchen ihn erneut. Du musst den Widerruf nicht erneut absenden.' ) . '</p><pre>' . esc_html( get_post_field( 'post_content', $id ) ) . '</pre>';
 } else {
  echo '<form method="post">'; wp_nonce_field( 'candy_withdrawal' );
  echo '<input type="hidden" name="token" value="' . esc_attr( $token ) . '"><input type="hidden" name="signature" value="' . esc_attr( hash_hmac( 'sha256', $token, wp_salt() ) ) . '">';
  if ( 'review' === $stage ) { echo '<h2>Widerruf prüfen</h2><p>Hiermit widerrufe ich den folgenden Vertrag bzw. die angegebenen Artikel.</p>'; }
  foreach ( array( 'name' => 'Vor- und Nachname', 'contract' => 'Bestellnummer oder andere Vertragsangabe; bei Teilwiderruf die Artikel', 'email' => 'E-Mail-Adresse für die Eingangsbestätigung' ) as $key => $label ) {
   echo '<label for="withdraw-' . esc_attr( $key ) . '">' . esc_html( $label ) . '</label>';
   $readonly = 'review' === $stage ? ' readonly' : '';
   if ( 'contract' === $key ) { echo '<textarea id="withdraw-contract" name="withdrawal_contract" rows="4" maxlength="2000" required' . $readonly . '>' . esc_textarea( $values[$key] ) . '</textarea>'; }
   else { echo '<input id="withdraw-' . esc_attr( $key ) . '" name="withdrawal_' . esc_attr( $key ) . '" type="' . ( 'email' === $key ? 'email' : 'text' ) . '" maxlength="' . ( 'email' === $key ? '254' : '150' ) . '" autocomplete="' . esc_attr( $key ) . '" value="' . esc_attr( $values[$key] ) . '" required' . $readonly . '>'; }
  }
  echo '<input type="hidden" name="candy_withdrawal_stage" value="' . ( 'review' === $stage ? 'confirm' : 'review' ) . '"><button class="button primary" type="submit">' . ( 'review' === $stage ? 'Widerruf bestätigen' : 'Vertrag widerrufen' ) . '</button>';
  if ( 'review' === $stage ) { echo '<p>Prüfe deine Angaben vor dem Absenden. Über die Zurück-Funktion deines Browsers kannst du sie bearbeiten.</p>'; }
  echo '</form>';
 }
 echo '</div>'; return ob_get_clean();
} );
